### ISSUE TITLE
Newest Commit Seemed to Break Something in getVisibleRegion()

### ISSUE THREAD

**Issue by KimberleeDArmstrong** [mapsplugin/v2.0-demo#41]
It is trying to access a nearRight function that doesn't exist for CameraPosition.

![screen shot 2017-06-07 at 5 41 33 pm](https://user-images.githubusercontent.com/9216004/26904731-0382b14a-4ba9-11e7-86eb-c75be92dd495.png)
![screen shot 2017-06-07 at 5 41 11 pm](https://user-images.githubusercontent.com/9216004/26904730-0381ea58-4ba9-11e7-8bac-c20983f067cf.png)

**Comment by wf9a5m75** [comment]
Ah, sorry, that code is for the next version.
Actually it's already fixed. So your code is old.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/www/Map.js#L581-L593

The current latest version is `2.0.0-beta2-20170606-1807`

**Comment by KimberleeDArmstrong** [comment]
I tried the newest version and the infowindows are popping up in various locations not with the marker and then I can't close them. 

Regards, 

Kimberlee Armstrong 
Software Engineer 
dataVoice International Inc. 
972-390-8808 X144

**Comment by wf9a5m75** [comment]
Please show me the screen record (video).

I have been working (battling) for ionic3 currently. Not for HTMLinfoWindow. So I haven't changed the code anything.

**Comment by KimberleeDArmstrong** [comment]
Sorry I put this in the wrong place on git hub.  Info Windows won't close and do weird things...
http://www.youtube.com/watch?v=VfL9z9-52G8

**Comment by wf9a5m75** [comment]
Ah, I see.
It seems you use old code and new code for HTMLinfoWindow.

**Comment by KimberleeDArmstrong** [comment]
I just changed all my code that looked like this....
var infoWindow = new plugin.google.maps.HtmlInfoWindow();
					infoWindow.setContent([content].join(""));
		 			var data = {
						icon: icon,
						position : {lat:searchresults[index].data.lat, lng:searchresults[index].data.lon},
						infoWindow: infoWindow,
						disableAutoPan:true,
						draggable: true,
						zIndex:120
					};
					googleMap.addMarker(data, function(marker) {
						marker.on(plugin.google.maps.event.MARKER_CLICK, function() {
							this.showInfoWindow();
						});
						var tmpdata = m;
						searchresults[index].marker=marker;
						searchresults[index].data = tmpdata;
					});

To look like this.....
var infoWindow = new plugin.google.maps.HtmlInfoWindow();
				infoWindow.setContent([content].join(""));
     			var data = {
					icon: 'images/' + getIcon('CON', 99) + '.png',
					position : {lat:searchresults[i].data.lat, lng:searchresults[i].data.lon},
					zIndex:120,
					draggable: true
				};
				googleMap.addMarker(data, function(marker) {
					marker.on(plugin.google.maps.event.MARKER_CLICK, function() {
						infoWindow.open(marker);
					});
					var tmpdata = m.data;
					searchresults[i].marker=marker;
					searchresults[i].data = tmpdata;
				});
And I am still getting the error.  What is wrong?

**Comment by wf9a5m75** [comment]
Could you tell me what version do you use? (cordoca plugin ls)

**Comment by wf9a5m75** [comment]
Could you show me the `cordova plugin list`?
The current version is `2.0.0-beta2-20170607-1043`

**Comment by KimberleeDArmstrong** [comment]
com.googlemaps.ios 2.2.0-fixed "Google Maps SDK for iOS"

**Comment by wf9a5m75** [comment]
I asked the version of the cordova-googlemaps-plugin

**Comment by KimberleeDArmstrong** [comment]
It is the top line

**Comment by KimberleeDArmstrong** [comment]
Sent an invite to bit bucket project.  If you just want to see the marker create and info window js you can focus on map_sdk.js - load_damage_markers(), load*DispMarkers()   and common_map_funcs_sdk.js - load_sub_markers(), load_media_markers(), showFakeSearchResults()

**Comment by wf9a5m75** [comment]
I can see only the README.md file.

**Comment by KimberleeDArmstrong** [comment]
Sorry I had been out of town.  Downloaded and tried latest version, and still having issue.  I have shared via bit bucket.  You should be able to see the files on this one.

**Comment by KimberleeDArmstrong** [comment]
Were you able to see the code?

**Comment by wf9a5m75** [comment]
Thank you for waiting. I have been processing issues one by one.

**Comment by KimberleeDArmstrong** [comment]
No worries, just making sure you weren't waiting on me still.

**Comment by wf9a5m75** [comment]
Let me confirm one thing. Is the repository name you invited me "dvAssessDamageSDK"?

**Comment by KimberleeDArmstrong** [comment]
Yes 

Regards, 

Kimberlee Armstrong 
Software Engineer 
dataVoice International Inc. 
972-390-8808 X144

**Comment by wf9a5m75** [comment]
Is it possible to load the source code from local instead of downloading?
It seems your code still uses old style code in multiple files.
But the code always is downloaded from your server.
So I can not debug your code.

**Comment by wf9a5m75** [comment]
I fixed the bug. Please reinstall the plugin.

![41](https://user-images.githubusercontent.com/167831/27522158-ae3796f4-59d8-11e7-9647-fa7858729af6.gif)

By the way, I warned to you before you hide the Google Maps logo that is positioned at bottom-left.
**This is against the terms of use of Google Maps API.**
This is strong warning.

I don't want to take part in the bad behavior, if you face any problems, I don't check your code until you fix it.
Please fix it as soon as possible.

**Comment by KimberleeDArmstrong** [comment]
It is much better, but I am still seeing some issues.  I was able to find what was causing the Google to be hidden and fixed that.  It was not intentional.
http://www.youtube.com/watch?v=WFqo6GNqcuY

**Comment by wf9a5m75** [comment]
Could you use the new style code in all your code?

**Comment by KimberleeDArmstrong** [comment]
Not sure I understand?  The file that the Google not showing fix was in is a shared file that is used by all my code.  "Sync Source Code" on Lineman App and Assess Damage and see the fix.

**Comment by wf9a5m75** [comment]
Your app downloads the code from `https://xxxxxxxxxxx/uploaded_files/appSource.zip`.
The archive has actual code of your app.
And, for example, in the `appmap.js` file, your code still uses old style.
![screen shot 2017-06-26 at 2 37 58 pm](https://user-images.githubusercontent.com/167831/27561509-40bc8d6e-5a7d-11e7-9ca4-e6c6158f51c4.png)

**Comment by KimberleeDArmstrong** [comment]
For the green "S" markers.  I am trying this code, but the marker won't close when I click the X.  What should I have....
/*----------------------------------------------------------------------------*/
function load_sub_markers() {
	/*for (var i = 0; i < subs.length; i++) {
		subs[i].hideInfoWindow();
	    subs[i].remove();
	}*/
	subs = [];
	var data=data=masterMarkerList['sub_markers'].rows;
	$.each(data,
	function(i, m) {
		var infoWindow = new plugin.google.maps.HtmlInfoWindow();
		infoWindow.setContent('<table>' + 
			'<tr><td></td><td align="right"><img src="images/close.png" onclick="javascript:subs['+i+'].infoWindow.close();"/></td></tr>' +
			'<tr><td class="popup_heading">Sub: </td><td class="popup_data">' + m.name + '</td></tr>' + 
			'<tr><td class="popup_heading">Total Meters: </td><td class="popup_data">' + m.total + '</td></tr>' +
			'<tr><td class="popup_heading">Meters Out: </td><td class="popup_data">' + m.out + '</td></tr>' +
			'<tr><td class="popup_heading">Percent On: </td><td class="popup_data">' + m.pct.toFixed(2) + '%</td></tr>' +
			'</table>');
		var data = {
			icon: cordova.file.dataDirectory+'www/images/'+m.image,
			position : {lat:m.lat, lng:m.lon},
			draggable: true,
			disableAutoPan:true,
			zIndex:10
		};
		//vehicles[i].popup = plugin.google.maps.InfoWindow({content: content, maxWidth: 400});
		googleMap.addMarker(data, function(marker) {
			//console.log(m.name);
			marker.data = m;
			marker.infoWindow = infoWindow;
			if (localStorage.getItem('ckbx_Substations') === 'false') {
				marker.setVisible(false);
			} else {
				marker.setVisible(true);
			}
			marker.on(plugin.google.maps.event.MARKER_CLICK, function() {
    			this.infoWindow.open(this);
    		});
    		subs.push(marker);
		});
	});
}
/*----------------------------------------------------------------------------*/

**Comment by wf9a5m75** [comment]
Did you check the safari inspector?
(I don't have my iOS device right now)

**Comment by wf9a5m75** [comment]
And in your code, you put `marker` instance to `subs`;

```js
subs.push(marker);
```

You can not do this `javascript:subs['+i+'].infoWindow.close();`. Because the marker does not have the `infoWindow` option.

**Comment by wf9a5m75** [comment]
You should do like this:

```js
function load_sub_markers() {
	
  var infoWindow = new plugin.google.maps.HtmlInfoWindow();
	subs = [];
	var data=data=masterMarkerList['sub_markers'].rows;
	$.each(data,
	function(i, m) {
	
		var data = {
			icon: cordova.file.dataDirectory+'www/images/'+m.image,
			position : {lat:m.lat, lng:m.lon},
			draggable: true,
			disableAutoPan:true,
			zIndex:10
		};
		//vehicles[i].popup = plugin.google.maps.InfoWindow({content: content, maxWidth: 400});
		googleMap.addMarker(data, function(marker) {
			//console.log(m.name);
			marker.data = m;
      marker.set("content", '<table>' + 
  			'<tr><td></td><td align="right"><img src="images/close.png" onclick="javascript:onCloseBtnClick();"/></td></tr>' +
  			'<tr><td class="popup_heading">Sub: </td><td class="popup_data">' + m.name + '</td></tr>' + 
  			'<tr><td class="popup_heading">Total Meters: </td><td class="popup_data">' + m.total + '</td></tr>' +
  			'<tr><td class="popup_heading">Meters Out: </td><td class="popup_data">' + m.out + '</td></tr>' +
  			'<tr><td class="popup_heading">Percent On: </td><td class="popup_data">' + m.pct.toFixed(2) + '%</td></tr>' +
  			'</table>');
        
			infoWindow.setContent();
			if (localStorage.getItem('ckbx_Substations') === 'false') {
				marker.setVisible(false);
			} else {
				marker.setVisible(true);
			}
			marker.on(plugin.google.maps.event.MARKER_CLICK, onMarkerClick);
    		subs.push(marker);
		});
	});

  function onMarkerClick() {
    var marker = this;
    var content = marker.get("content");
    infoWindow.open(marker);
  }
  function onCloseBtnClick() {
    infoWindow.close();
  }
}
```

**Comment by wf9a5m75** [comment]
More optimized code is 

```js
function load_sub_markers() {

  var infoWindow = new plugin.google.maps.HtmlInfoWindow();
  subs = [];
  var data = masterMarkerList['sub_markers'].rows;
  var baseArray = new plugin.google.maps.BaseArrayClass(data);
  baseArray.map(function(myData, i) {

    var data = {
      icon: cordova.file.dataDirectory + 'www/images/' + myData.image,
      position: {
        lat: myData.lat,
        lng: myData.lon
      },
      draggable: true,
      disableAutoPan: true,
      zIndex: 10,
      visible: localStorage.getItem('ckbx_Substations') === 'true',
      myData: myData
    };
    //vehicles[i].popup = plugin.google.maps.InfoWindow({content: content, maxWidth: 400});
    googleMap.addMarker(data, cb);

  }, function(markers) {

    subs = markers;
    markers.forEach(function(marker) {
      marker.on(plugin.google.maps.event.MARKER_CLICK, onMarkerClick);
    });
  });

  function onMarkerClick() {
    var marker = this;
    var myData = marker.get("myData");

    var content ='<table>' +
      '<tr><td></td><td align="right"><img src="images/close.png" onclick="javascript:onCloseBtnClick();"/></td></tr>' +
      '<tr><td class="popup_heading">Sub: </td><td class="popup_data">' + myData.name + '</td></tr>' +
      '<tr><td class="popup_heading">Total Meters: </td><td class="popup_data">' + myData.total + '</td></tr>' +
      '<tr><td class="popup_heading">Meters Out: </td><td class="popup_data">' + myData.out + '</td></tr>' +
      '<tr><td class="popup_heading">Percent On: </td><td class="popup_data">' + myData.pct.toFixed(2) + '%</td></tr>' +
      '</table>';
    infoWindow.setContent(content);

    infoWindow.open(marker);
  }

  function onCloseBtnClick() {
    infoWindow.close();
  }
}

```

**Comment by KimberleeDArmstrong** [comment]
Thank you.  I will change all of my marker functions and test today.

**Comment by KimberleeDArmstrong** [comment]
Do I need a plugin update for this?  I am getting "cb" is undefined error.  I tried to change to code to make it work but then got "forEach" is not a function of marker.

**Comment by wf9a5m75** [comment]
Please use the latest version of the plugin.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/BaseArrayClass/map/README.md#mapfn-callback

**Comment by wf9a5m75** [comment]
Just for helping.

```js
var baseArray = new plugin.google.maps.BaseArrayClass([item1, item2, ... itemN]);

baseArray.map(function(item, callback) {

  var result = item;  // what ever you want

  callback(result);

}, function(results) {
 
  // results is just an array of normal JavaScript.

});
```

**Comment by KimberleeDArmstrong** [comment]
ok.  I get it.  I am using the latest version of the plugin and the most recent code.  I am getting "can't find variable: onCloseBtnClick" .  I am trying to figure that one out.

**Comment by wf9a5m75** [comment]
onCloseBtnClick is a function.

**Comment by KimberleeDArmstrong** [comment]
I know but for whatever reason in the code I copy and pasted from you, it is not recognizing it. :-(

**Comment by wf9a5m75** [comment]
Uh, maybe 

```js
window. onCloseBtnClick =  function() {
    infoWindow.close();
};

```

**Comment by wf9a5m75** [comment]
Actually proper JS way is

```js
function onMarkerClick() {
    var marker = this;
    var myData = marker.get("myData");
    var table = document.createElement("table");
    table.innerHTML = 
      '<tr><td></td><td align="right"><img src="images/close.png" id="closeBtn"/></td></tr>' +
      '<tr><td class="popup_heading">Sub: </td><td class="popup_data">' + myData.name + '</td></tr>' +
      '<tr><td class="popup_heading">Total Meters: </td><td class="popup_data">' + myData.total + '</td></tr>' +
      '<tr><td class="popup_heading">Meters Out: </td><td class="popup_data">' + myData.out + '</td></tr>' +
      '<tr><td class="popup_heading">Percent On: </td><td class="popup_data">' + myData.pct.toFixed(2) + '%</td></tr>';

    var closeBtn = table.getElementById("closeBtn");
    closeBtn.addEventListener("click", function() {
      infoWindow.close();
    });

    infoWindow.setContent(table);

    infoWindow.open(marker);
}
```

**Comment by KimberleeDArmstrong** [comment]
I was able to get it working like this...

function onMarkerClick() {
    var marker = this;
    var myData = marker.get("myData");
    var content = 
      '<table> <tr><td></td><td id="closeBtn" align="right"><img src="images/close.png"/></td></tr>' +
      '<tr><td class="popup_heading">Sub: </td><td class="popup_data">' + myData.name + '</td></tr>' +
      '<tr><td class="popup_heading">Total Meters: </td><td class="popup_data">' + myData.total + '</td></tr>' +
      '<tr><td class="popup_heading">Meters Out: </td><td class="popup_data">' + myData.out + '</td></tr>' +
      '<tr><td class="popup_heading">Percent On: </td><td class="popup_data">' + myData.pct.toFixed(2) + '%</td></tr></table>';
    infoWindow.setContent(content);
    infoWindow.open(marker);
    setTimeout( function() {
    $("#closeBtn").on("click", function() {
		    infoWindow.close();
    });
    },500);
}

I try to steer clear of setTimeout's as much as possible but this is the only way I could get anything to work.  Do you think its ok?  The code you gave was giving error table.getElementById is not a function. 

If this looks good I will start refactoring all of our apps marker functions.

**Comment by wf9a5m75** [comment]
I forgot jQuery recently, but I think you can do something like this:

```js
function onMarkerClick() {
    var marker = this;
    var myData = marker.get("myData");
    var content = 
      '<table> <tr><td></td><td id="closeBtn" align="right"><img src="images/close.png"/></td></tr>' +
      '<tr><td class="popup_heading">Sub: </td><td class="popup_data">' + myData.name + '</td></tr>' +
      '<tr><td class="popup_heading">Total Meters: </td><td class="popup_data">' + myData.total + '</td></tr>' +
      '<tr><td class="popup_heading">Meters Out: </td><td class="popup_data">' + myData.out + '</td></tr>' +
      '<tr><td class="popup_heading">Percent On: </td><td class="popup_data">' + myData.pct.toFixed(2) + '%</td></tr></table>';
    infoWindow.setContent(content);
    infoWindow.open(marker);

    var jqContent = $(content);
    jqContent.find("#closeBtn").on("click", function() {
		    infoWindow.close();
    });
}
```

**Comment by wf9a5m75** [comment]
@KimberleeDArmstrong ping

**Comment by KimberleeDArmstrong** [comment]
I am still rewriting everything, but so far so good!

**Comment by wf9a5m75** [comment]
Ok. Sounds good.
